const streets = [
    // "Jackson",
    // "Vine",
    // "Skinner",
    // "Mills",
    // "Branch",
    // "Myer",
    // "Linton",
    // "Lake St",
    // "Fair",
    // "Bank",
    // "Carr",
    // "Newland",
    // "Hoek",
    // "Walter",
    // "John",
    // "Crosstown",
    // "Boerman",
    // "Upjohn",
    // "Burdick",
    // "Rose",
    // "Wall",
    // "Houston",
    // "Burr Oak",
    // "Vandersalm",
    // "Dutton",
    // "Wilrad",
    // "Jasper",
    // "Heilman",
    // "Van Vranken",
    // "Cedar",
    // "Lovell",
    // "Gibson",
    // "Fisher",
    // "Smith",
    // "Hibbard",
    // "Foresman",
    // "Henry",
    // "Burke",
    // "Schippers",
    // "Oonah",
    // "Openings",
    // "Dells",
    // "Elder",
    // "Fenimore",
    // "Chicago",
    // "Cooper",
    // "Washburn",
    // "Ira",
    // "Dearborn",
    // "Charles",
    // "Coy",
    // "Briar",
    // "Lake",
    // "Inkster",
    // "Creston",
    // "Monstrose",
    // "Edgemore",
    // "Fairview",
    // "Garland",
    // "Whitcomb",
    // "Fairfax",
    // "Law",
    // "Plymouth",
    // "Ridgewood",
    // "Cork",
    // "Albany",
    // "Garfield",
    // "Hughes",
    // "Ash",
    // "Hutchinson",
    // "Pierce",
    // "Parker",
    // "Buchanan",
    // "Deloofs",
    // "Leona",
    // "Peekstok",
    // "Ryskamp",
    // "Locust",
    // "Oak",
    // "Pearl",
    // "Walnut",
    // "Davis",
    // "Normal",
    // "Bellevue",
    // "Academy",
    // "Acker",
    // "Thompson",
    // "Summit",
    // "Bulkley",
    // "Blakeslee",
    // "Alamo",
    // "Forest",
    // "Potter",
    // "Duffield",
    // "Hoffman",
    // "Walwood",
    // "Lee Barton",
    // "Austin",
    // "Grant",
    
    // "Clarence",
    // "Emerson",
    // "Belmont",																									
    // "Dixie",																									
    // "Stetson",																									
    // "Haveman",																									
    // "Remine",																								
    // "Kalanco",																									
    // "Ravina",
    // "Imperial",	
    // "Oakhurst",
    // "Pratt",
    // "Candlewyck",
    // "Lafayette",
    // "Euclid",
    // "Greenwood",
    // "Kimbark",
    // "Redwood",
    // "Sutherland",
    // "Knollwood",
    // "Willard",
    // "Harkins",
    // "Ransom",
    // "Reverend",
    // "Butler",
    // "Gull",
    // "Caves",
    // "Butler",
    // "North",
//     "Frank",
//     "Myrtle",
//     "Parsons",
//     "Richardson",
//     "Drexel",
//     "Paterson",
//     "Bush",
//     "Norway",
//     "Mabel",
//     "Florence",
// "Lawrence",
// "Nola",
// "Ada",
// "Elizabeth",
// "William",
// "Conant",
// "Jefferson",
// "Ransom",
// "Hilbert",
// "Denner",
// "Summer",
// "Hawley",
// "Staples",
// "Woodward",
// "Cobb",
// "Simpson",
// "Woodbury",
// "Church",
// "Edwards",
// "Scudder",																									
"Pitcher",																									
"Porter",																								
"Dunkley",																									
"Hopkins",																									
"Prouty",																								
"Clay",																									
"Union",																									
"Krom",																									
"Edwards",																									
"Martin",																									
"Herbert",																									
"Princeton",																									
"Lulu",																									
"Bosker",																								
"Harding",																									
"Holland",																									
"William",																									
"Interfaith",																								
"Dennis",																									
"Douglas",																									


]

module.exports = streets;

